languageCode = "en-us"
title = "rmarketing.io"
baseURL = "http://rmarketing.io/blog/"
theme = "hyde"

[params]
  Author = "Matthias Bannert"
  disqusShortname = "matthiasbannert"
  themeColor = "theme-base-0e"
