languageCode = "en-us"
title = "rmarketing.io"
baseURL = "http://rmarketing.io/blog/"
theme = "hyde"

[params]
  disqusShortname = "blog-rmarketing-io"
  Author = "Matthias Bannert"
  themeColor = "theme-base-0d"
